{% set name = "Nuitka" %}
{% set version = "1.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 729806f45d8a7cf45a843a92752f392e6a821653ba72d46505b6c154be0d3853

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - nuitka = nuitka.__main__:main
    - nuitka-run = nuitka.__main__:main

requirements:
  host:
    - python
    - libpython-static  # [not win]
    - pip
    - setuptools
    - wheel
  run:
    - python
    - libpython-static  # [not win]
    - ordered-set >=4.1.0
    - zstandard >=0.15

test:
  imports:
    - nuitka
    - nuitka.build
    - nuitka.containers
    - nuitka.finalizations
    - nuitka.freezer
    - nuitka.importing
    - nuitka.nodes
    - nuitka.optimizations
    - nuitka.plugins
    - nuitka.specs
    - nuitka.tools
    - nuitka.tree
    - nuitka.utils
  requires:
    - pip
    - {{ compiler('c') }}  # [linux]
  commands:
    - pip check
    - nuitka --help
    - nuitka-run --help
    - python -m nuitka --version

about:
  home: https://nuitka.net
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python compiler with full language support and CPython compatibility
  description: |
    Nuitka is the Python compiler. It is a seamless replacement or extension
    to the Python interpreter and compiles every construct that CPython 2.6,
    2.7, 3.3, 3.4, 3.5, 3.6, and 3.7 have. It then executes uncompiled code,
    and compiled code together in an extremely compatible manner.

    You can use all Python library modules or and all extension modules freely.
    It translates the Python into a C level program that then uses "libpython"
    to execute in the same way as CPython does. All optimization is aimed at
    avoiding overhead, where it's unnecessary. None is aimed at removing
    compatibility, although slight improvements will occassionally be done,
    where not every bug of standard Python is emulated, e.g. more complete
    error messages are given, but there is a full compatibility mode to
    disable even that.
  doc_url: https://nuitka.net/doc/user-manual.html
  dev_url: https://github.com/Nuitka/Nuitka

extra:
  recipe-maintainers:
    - frol
    - kayhayen
