{% set name = "Nuitka" %}
{% set version = "2.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ad661b57dec9753ca93c59232bf40bc3288d79da46492cc574cfca640d81d13
  patches:
    - patches/0001-Remove-vendored-zlib-and-zstd-from-setup.py.patch

build:
  number: 0
  script_env:
    - NUITKA_NO_INLINE_COPY=1
    - NUITKA_ASSUME_YES_FOR_DOWNLOADS=1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - nuitka = nuitka.__main__:main
    - nuitka-run = nuitka.__main__:main

requirements:
  build:
    - patch  # [unix]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - scons 4.1.0.post1
    - zlib
    - zstd
  run:
    - python
    - libpython-static  # [not win]
    - ordered-set >=4.1.0  # [py>=37]
    - orderedset >=2.0.3  # [py<37]
    - zstandard >=0.15  # [py>=35]
    - jinja2 >=2.10.2
     # Was addInlineCopy()
    - appdirs
    - glob2
    - markupsafe
    - tqdm
    - atomicwrites # [win]
    - clcache # [win]
    - colorama # [win]
    - pefile # [win]
    - pyyaml  # [py>=36]
    - jinja2  # [py>=36]
    # XXX pkg_resources is bundled with setuptools now (or something)
    #- pkg_resources
    #- bin  # ??
    - scons 4.1.0.post1
    - zlib
    - zstd

test:
  imports:
    - nuitka
    - nuitka.build
    - nuitka.containers
    - nuitka.finalizations
    - nuitka.freezer
    - nuitka.importing
    - nuitka.nodes
    - nuitka.optimizations
    - nuitka.plugins
    - nuitka.specs
    - nuitka.tools
    - nuitka.tree
    - nuitka.utils
  requires:
    - pip
    - {{ compiler('c') }}
    - scons 4.1.0.post1  # [win]
  commands:
    - pip check
    - nuitka --help
    - nuitka-run --help
    - python -m nuitka --version
    - touch Empty.py  # [unix]
    - python -c "open('Empty.py', 'w').close()"  # [win]
    # Disable ccache in the test compilation because of the frozen prompt
    - nuitka --show-scons --run --verbose --disable-ccache --msvc=14.3 --assume-yes-for-downloads Empty.py  # [win]
    - nuitka --show-scons --run --verbose --disable-ccache Empty.py  # [unix]

about:
  home: https://nuitka.net
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python compiler with full language support and CPython compatibility
  description: |
    Nuitka is the Python compiler. It is a seamless replacement or extension
    to the Python interpreter and compiles every construct that CPython 2.6,
    2.7, 3.3, 3.4, 3.5, 3.6, and 3.7 have. It then executes uncompiled code,
    and compiled code together in an extremely compatible manner.

    You can use all Python library modules or and all extension modules freely.
    It translates the Python into a C level program that then uses "libpython"
    to execute in the same way as CPython does. All optimization is aimed at
    avoiding overhead, where it's unnecessary. None is aimed at removing
    compatibility, although slight improvements will occassionally be done,
    where not every bug of standard Python is emulated, e.g. more complete
    error messages are given, but there is a full compatibility mode to
    disable even that.
  doc_url: https://nuitka.net/doc/user-manual.html
  dev_url: https://github.com/Nuitka/Nuitka

extra:
  recipe-maintainers:
    - frol
    - kayhayen
