travis:
  secure:
    BINSTAR_TOKEN: uwfJi4SVASdV21Q+4bUMlqonRfe8cac8NinfXMNdGhWUdaTVLkrSArDu5O37I1NaW+aw+38tD+jNeoYe9aDL4kjyU9vg4OMxXb4gkmi0Zsl75OZ0JHXdxZ+wGLUWviGAiFhvW2kV1SqGZglc2aRfczI5l3wxvr9934tQ/p006ybXvM77gKAGKKNgo4eHJV/rk255Fx+Y4+qw79Rs7pwV5gWOsVBqbbHEFqiliYEqHVeRxDYAf/8CifV3VjdpXAfrH099o6v3NyqZR3cPxQhwFH4qzRTuKiNvfqIf3RF/I4mQasNORkgG2UtoFsfQ3VtHExMY8/8lzKi7Q1ITdK+QqHesQQ0d8MX3OvAtTbP3YdXSby3ko2jIfp9qK+UjdPXXaJsmMkz05DZGcG8PJWZXjOHtmrBHxIs6F7SaEWMgJ2C0tfRi3wdIy9CRTiR1SpBOS9XdBfp1oH5j5+FT5ZT8gf2gUzqjThqGAuwqn2ZNX2gjyH70LdZukgijGW50WOmAjP/bkWLjuZh0E1cyICdal+QQiglW/zrerLnL+b0oh+Z3LdG9i//Uj1MCBy8PSmxT/5QyApHlrbuBG/5lH5cSD7aOlSC9u4336cc+Zc1TpqHHoeLwDuXSwplokvKoHqRfMJFfGxzThPsWD/mphZxntN5CN93oZHHCn10iLegMenI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
