travis:
  secure:
    BINSTAR_TOKEN: n4Z6WPWyXHw+wdvONBVbBsJBOQyfzvN59gUqqtXSUeER9X6FE7Fogmu2Qp64M3DHxEdPS2NrtIupDo8pNJqVCoxq8XW+9jUvml1kBqmmNl8n5RhjXmBJITsi4Ye43ANeroEblRPr1NqfFVg4+aAwu/6zUSHtHAhbvWAq3ZazG214gb4ONJc1cRUwSedkZK24BqbsacJ89LI/ILPyGw1kbX1LXLO9V1mPagpqVAmJ9DO6LSza1QFicnk5L4Yzml9Kwd4rtcykLYtF/Y/mn1rbf98J93cm7fRUmb182X75ExLEvqasqKXhN1UgdGtkOXEawRrYhIgahOEjqu3n0Ki0PMzBTJ1jwG9g4lgeWjWUg/Nu8oCQo/trBdWRRbMJKVjPjhXnDWc0c8IixFVB0bCqFF8Fy51o46doqDv+EJ2q9++UmPJse4L8TwNiApWE92/TjLut45Kq27k5957gsRgSIaHU32tf70LdLHsI93s7ygATZEnTfdJRFy/2E6NH0iuY05uBsI+4DLFaTK+RkHQTokvTyl6z43fmBAl+A4iNB9BEe1bmVjJI0jgvNuOQa8PKGViF6uJtCSfhAUhvY9N6FXW2ICZcXuIz7AgePfAHtM0nU1J+lcokmS/9RarnJveXJLpspVbH15WQOsuT/rsicRW2Lmo5sKbCN9AM2z7Py4k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
