travis:
  secure:
    BINSTAR_TOKEN: RvTbxfkXjyHULZcBsj5ilQqzQGm0vsjoen5Q+Oaf8RMH7PBq2B9efvJcgysZc1IbCZfQ8IzjFFCAWA6qUQ8inxkJd3X8kut8sduTRixkVV56dbM/w5v/ZX2mX+yDkxmekkfZSMuIR2jRZu8Nwohh53E2r305bKrsHx0YjHtU8CjBNnvM4Rj/xvud/mJgBTwIiaMqhNFXB3vy/qq95fGAOm8AXwe+D/bUJfanXh6CAKKICmCPNWGjj+2J9W6GfoupDP1hiTPFE22zk8exCHGABwZRinYnpIzXAPjOSNS/EhRpuzczH28YZRUFl+wRAUhHRvZQV2uoTqv2snrtCFU3kyXzVOW5+33JZJDw2RQac1hUI5xh/rLnkPE3WnePYx1J0fCrmlpJwOb7hTYBPXxvfVldwWAvo+0Qnzd3zh2fqLR9h10FSdrATFfXaahBNHxijZ6m09a6+LoVrlmIj/COZA8+EWiSKeJE9P2BRvKucoKXyKh+nJxIy/htrHQKQFxzAwvgaX7KdiX9+6ZWW+rz+J6clFnvZ650DaKe+kiHO3QOy/CZ/OECk4A99SEnjUHZRRcCDLJyINJp7EQHixbRDyG85SFdZC99nJXo8IEi0mcgIMyQhyFX7biaBIDK8fhIWSgSNIvK2ENA1hKlhFlgSLSXOo3toTn6tWJ7BPDwEsw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
